version: "3.5"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on: 
            - database
        env_file:
            - .env
        ports:
            - "3000:3000"
    database:
        platform: linux/amd64
        image: mysql:5.7
        restart: always
        ports:
        - 3306:3306
        env_file:
        - .env
        volumes:
        - ~/database/spotcar:/var/lib/mysql
